# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.

import unittest
import gcp.bigquery as bq


class TestCases(unittest.TestCase):

  def test_repeating_data(self):
    schema = [{'name': 'counts', 'type': 'INTEGER', 'mode': 'REPEATED'}]
    data = {'f': [{'v': [{'v': 0}, {'v': 1}, {'v': 2}]}]}
    parsed = {'counts': [0, 1, 2]}
    result = bq._parser.Parser.parse_row(schema, data)
    self.assertEqual(parsed, result)


  def test_non_nested_data(self):

    data = {u'f': [{u'v': u'1969'},
                   {u'v': u'1969'},
                   {u'v': u'1'},
                   {u'v': u'20'},
                   {u'v': None},
                   {u'v': u'AL'},
                   {u'v': u'true'},
                   {u'v': u'1'},
                   {u'v': u'7.81318256528'},
                   {u'v': None},
                   {u'v': None},
                   {u'v': None},
                   {u'v': u'AL'},
                   {u'v': u'1'},
                   {u'v': u'20'},
                   {u'v': None},
                   {u'v': u'88881998'},
                   {u'v': u'true'},
                   {u'v': u''},
                   {u'v': None},
                   {u'v': None},
                   {u'v': None},
                   {u'v': None},
                   {u'v': None},
                   {u'v': u'1'},
                   {u'v': u'0'},
                   {u'v': u'0'},
                   {u'v': u'2'},
                   {u'v': u'1'},
                   {u'v': u'19'},
                   {u'v': u'2'}]}

    natality_schema = [{u'description': u'Four-digit year of the birth. Example: 1975.',
                        u'mode': u'REQUIRED',
                        u'name': u'source_year',
                        u'type': u'INTEGER'},
                       {u'description': u'Four-digit year of the birth. Example: 1975.',
                        u'mode': u'NULLABLE',
                        u'name': u'year',
                        u'type': u'INTEGER'},
                       {u'description': u'Month index of the date of birth, where 1=January.',
                        u'mode': u'NULLABLE',
                        u'name': u'month',
                        u'type': u'INTEGER'},
                       {u'description': u'Day of birth, starting from 1.',
                        u'mode': u'NULLABLE',
                        u'name': u'day',
                        u'type': u'INTEGER'},
                       {u'description': u'Day of the week, where 1 is Sunday and 7 is Saturday.',
                        u'mode': u'NULLABLE',
                        u'name': u'wday',
                        u'type': u'INTEGER'},
                       {u'description': u'The two character postal code for the state. Entries after 2004 do not include this value.',
                        u'mode': u'NULLABLE',
                        u'name': u'state',
                        u'type': u'STRING'},
                       {u'description': u'TRUE if the child is male, FALSE if female.',
                        u'mode': u'REQUIRED',
                        u'name': u'is_male',
                        u'type': u'BOOLEAN'},
                       {u'description': u'The race of the child. One of the following numbers:\n\n1 - White\n2 - Black\n3 - American Indian\n4 - Chinese\n5 - Japanese\n6 - Hawaiian\n7 - Filipino\n9 - Unknown/Other\n18 - Asian Indian\n28 - Korean\n39 - Samoan\n48 - Vietnamese',
                        u'mode': u'NULLABLE',
                        u'name': u'child_race',
                        u'type': u'INTEGER'},
                       {u'description': u'Weight of the child, in pounds.',
                        u'mode': u'NULLABLE',
                        u'name': u'weight_pounds',
                        u'type': u'FLOAT'},
                       {u'description': u'How many children were born as a result of this pregnancy. twins=2, triplets=3, and so on.',
                        u'mode': u'NULLABLE',
                        u'name': u'plurality',
                        u'type': u'INTEGER'},
                       {u'description': u'Apgar scores measure the health of a newborn child on a scale from 0-10. Value after 1 minute. Available from 1978-2002.',
                        u'mode': u'NULLABLE',
                        u'name': u'apgar_1min',
                        u'type': u'INTEGER'},
                       {u'description': u'Apgar scores measure the health of a newborn child on a scale from 0-10. Value after 5 minutes. Available from 1978-2002.',
                        u'mode': u'NULLABLE',
                        u'name': u'apgar_5min',
                        u'type': u'INTEGER'},
                       {u'description': u"The two-letter postal code of the mother's state of residence when the child was born.",
                        u'mode': u'NULLABLE',
                        u'name': u'mother_residence_state',
                        u'type': u'STRING'},
                       {u'description': u'Race of the mother. Same values as child_race.',
                        u'mode': u'NULLABLE',
                        u'name': u'mother_race',
                        u'type': u'INTEGER'},
                       {u'description': u'Reported age of the mother when giving birth.',
                        u'mode': u'NULLABLE',
                        u'name': u'mother_age',
                        u'type': u'INTEGER'},
                       {u'description': u'The number of weeks of the pregnancy.',
                        u'mode': u'NULLABLE',
                        u'name': u'gestation_weeks',
                        u'type': u'INTEGER'},
                       {u'description': u'Date of the last menstrual period in the format MMDDYYYY. Unknown values are recorded as "99" or "9999".',
                        u'mode': u'NULLABLE',
                        u'name': u'lmp',
                        u'type': u'STRING'},
                       {u'description': u'True if the mother was married when she gave birth.',
                        u'mode': u'NULLABLE',
                        u'name': u'mother_married',
                        u'type': u'BOOLEAN'},
                       {u'description': u"The two-letter postal code of the mother's birth state.",
                        u'mode': u'NULLABLE',
                        u'name': u'mother_birth_state',
                        u'type': u'STRING'},
                       {u'description': u'True if the mother smoked cigarettes. Available starting 2003.',
                        u'mode': u'NULLABLE',
                        u'name': u'cigarette_use',
                        u'type': u'BOOLEAN'},
                       {u'description': u'Number of cigarettes smoked by the mother per day. Available starting 2003.',
                        u'mode': u'NULLABLE',
                        u'name': u'cigarettes_per_day',
                        u'type': u'INTEGER'},
                       {u'description': u'True if the mother used alcohol. Available starting 1989.',
                        u'mode': u'NULLABLE',
                        u'name': u'alcohol_use',
                        u'type': u'BOOLEAN'},
                       {u'description': u'Number of drinks per week consumed by the mother. Available starting 1989.',
                        u'mode': u'NULLABLE',
                        u'name': u'drinks_per_week',
                        u'type': u'INTEGER'},
                       {u'description': u'Number of pounds gained by the mother during pregnancy.',
                        u'mode': u'NULLABLE',
                        u'name': u'weight_gain_pounds',
                        u'type': u'INTEGER'},
                       {u'description': u'Number of children previously born to the mother who are now living.',
                        u'mode': u'NULLABLE',
                        u'name': u'born_alive_alive',
                        u'type': u'INTEGER'},
                       {u'description': u'Number of children previously born to the mother who are now dead.',
                        u'mode': u'NULLABLE',
                        u'name': u'born_alive_dead',
                        u'type': u'INTEGER'},
                       {u'description': u'Number of children who were born dead (i.e. miscarriages)',
                        u'mode': u'NULLABLE',
                        u'name': u'born_dead',
                        u'type': u'INTEGER'},
                       {u'description': u'Total number of children to whom the woman has ever given birth (includes the current birth).',
                        u'mode': u'NULLABLE',
                        u'name': u'ever_born',
                        u'type': u'INTEGER'},
                       {u'description': u'Race of the father. Same values as child_race.',
                        u'mode': u'NULLABLE',
                        u'name': u'father_race',
                        u'type': u'INTEGER'},
                       {u'description': u'Age of the father when the child was born.',
                        u'mode': u'NULLABLE',
                        u'name': u'father_age',
                        u'type': u'INTEGER'},
                       {u'description': u'1 or 2, where 1 is a row from a full-reporting area, and 2 is a row from a 50% sample area.',
                        u'mode': u'NULLABLE',
                        u'name': u'record_weight',
                        u'type': u'INTEGER'}]

    parsed = {u'alcohol_use': None,
              u'apgar_1min': None,
              u'apgar_5min': None,
              u'born_alive_alive': 1,
              u'born_alive_dead': 0,
              u'born_dead': 0,
              u'child_race': 1,
              u'cigarette_use': None,
              u'cigarettes_per_day': None,
              u'day': 20,
              u'drinks_per_week': None,
              u'ever_born': 2,
              u'father_age': 19,
              u'father_race': 1,
              u'gestation_weeks': None,
              u'is_male': True,
              u'lmp': u'88881998',
              u'month': 1,
              u'mother_age': 20,
              u'mother_birth_state': u'',
              u'mother_married': True,
              u'mother_race': 1,
              u'mother_residence_state': u'AL',
              u'plurality': None,
              u'record_weight': 2,
              u'source_year': 1969,
              u'state': u'AL',
              u'wday': None,
              u'weight_gain_pounds': None,
              u'weight_pounds': 7.81318256528,
              u'year': 1969}

    self.assertEqual(parsed, bq._parser.Parser.parse_row(natality_schema, data))

  def test_parse_nested_data(self):

    self.maxDiff = None  # Show full diff on failure
    data = {u'f': [{u'v': {u'f': [{u'v': u'https://github.com/foo'},
                                  {u'v': u'true'},
                                  {u'v': u'2011/04/12 20:04:19 -0700'},
                                  {u'v': u'true'},
                                  {u'v': u'A website.'},
                                  {u'v': u'17'},
                                  {u'v': u'false'},
                                  {u'v': u'true'},
                                  {u'v': u'http://foo.com/'},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': u'424'},
                                  {u'v': u'false'},
                                  {u'v': u'foo'},
                                  {u'v': None},
                                  {u'v': u'foo'},
                                  {u'v': u'0'},
                                  {u'v': u'95'},
                                  {u'v': u'2012/03/15 00:00:00 -0700'},
                                  {u'v': u'Ruby'}]}},
                   {u'v': {u'f': [{u'v': u'http://foo.com/'},
                                  {u'v': u'Flickr'},
                                  {u'v': u'd+github@foo.com'},
                                  {u'v': u'94c21234567890abcdef25e704b88407'},
                                  {u'v': u'San Francisco, California'},
                                  {u'v': u'foo'},
                                  {u'v': u'Foo Bar'},
                                  {u'v': u'User'}]}},
                   {u'v': u'2012/03/15 00:00:01 -0700'},
                   {u'v': u'true'},
                   {u'v': u'foo'},
                   {u'v': {u'f': [{u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': u'2de950123456789abcdef01234451feaf8ce6ae'},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': None},
                                  {u'v': []},
                                  {u'v': None},
                                  {u'v': u'refs/heads/master'},
                                  {u'v': None},
                                  {u'v': u'1'},
                                  {u'v': [{u'v': {u'f': [{u'v': u'2de958ab480eabe2501b343425b451feaf8ce6ae'},
                                                         {u'v': u'd+github@foo.com'},
                                                         {u'v': u'Foo tastes good.'},
                                                         {u'v': u'Foo Bar'}]}}]},
                                  {u'v': None},
                                  {u'v': None}]}},
                   {u'v': u'https://github.com/compare/d3e91cb736...2de958ab48'},
                   {u'v': u'PushEvent'}]}

    github_nested_schema = [{u'fields': [{u'name': u'url', u'type': u'STRING'},
                                         {u'name': u'has_downloads', u'type': u'BOOLEAN'},
                                         {u'name': u'created_at', u'type': u'STRING'},
                                         {u'name': u'has_issues', u'type': u'BOOLEAN'},
                                         {u'name': u'description', u'type': u'STRING'},
                                         {u'name': u'forks', u'type': u'INTEGER'},
                                         {u'name': u'fork', u'type': u'BOOLEAN'},
                                         {u'name': u'has_wiki', u'type': u'BOOLEAN'},
                                         {u'name': u'homepage', u'type': u'STRING'},
                                         {u'name': u'integrate_branch', u'type': u'STRING'},
                                         {u'name': u'master_branch', u'type': u'STRING'},
                                         {u'name': u'size', u'type': u'INTEGER'},
                                         {u'name': u'private', u'type': u'BOOLEAN'},
                                         {u'name': u'name', u'type': u'STRING'},
                                         {u'name': u'organization', u'type': u'STRING'},
                                         {u'name': u'owner', u'type': u'STRING'},
                                         {u'name': u'open_issues', u'type': u'INTEGER'},
                                         {u'name': u'watchers', u'type': u'INTEGER'},
                                         {u'name': u'pushed_at', u'type': u'STRING'},
                                         {u'name': u'language', u'type': u'STRING'}],
                             u'name': u'repository',
                             u'type': u'RECORD'},
                            {u'fields': [{u'name': u'blog', u'type': u'STRING'},
                                         {u'name': u'company', u'type': u'STRING'},
                                         {u'name': u'email', u'type': u'STRING'},
                                         {u'name': u'gravatar_id', u'type': u'STRING'},
                                         {u'name': u'location', u'type': u'STRING'},
                                         {u'name': u'login', u'type': u'STRING'},
                                         {u'name': u'name', u'type': u'STRING'},
                                         {u'name': u'type', u'type': u'STRING'}],
                             u'name': u'actor_attributes',
                             u'type': u'RECORD'},
                            {u'name': u'created_at', u'type': u'STRING'},
                            {u'name': u'public', u'type': u'BOOLEAN'},
                            {u'name': u'actor', u'type': u'STRING'},
                            {u'fields': [{u'name': u'action', u'type': u'STRING'},
                                         {u'name': u'after', u'type': u'STRING'},
                                         {u'name': u'before', u'type': u'STRING'},
                                         {u'name': u'commit', u'type': u'STRING'},
                                         {u'fields': [{u'name': u'commit_id', u'type': u'STRING'},
                                                      {u'name': u'body', u'type': u'STRING'},
                                                      {u'name': u'created_at', u'type': u'STRING'},
                                                      {u'name': u'id', u'type': u'INTEGER'},
                                                      {u'name': u'original_commit_id', u'type': u'STRING'},
                                                      {u'name': u'original_position', u'type': u'INTEGER'},
                                                      {u'name': u'path', u'type': u'STRING'},
                                                      {u'name': u'position', u'type': u'INTEGER'},
                                                      {u'name': u'updated_at', u'type': u'STRING'},
                                                      {u'fields': [{u'name': u'id', u'type': u'INTEGER'},
                                                                   {u'name': u'gravatar_id', u'type': u'STRING'},
                                                                   {u'name': u'avatar_url', u'type': u'STRING'},
                                                                   {u'name': u'login', u'type': u'STRING'},
                                                                   {u'name': u'url', u'type': u'STRING'}],
                                                       u'name': u'user',
                                                       u'type': u'RECORD'},
                                                      {u'name': u'url', u'type': u'STRING'}],
                                          u'name': u'comment',
                                          u'type': u'RECORD'},
                                         {u'name': u'comment_id', u'type': u'INTEGER'},
                                         {u'name': u'desc', u'type': u'STRING'},
                                         {u'name': u'description', u'type': u'STRING'},
                                         {u'name': u'head', u'type': u'STRING'},
                                         {u'name': u'id', u'type': u'INTEGER'},
                                         {u'name': u'issue', u'type': u'INTEGER'},
                                         {u'name': u'issue_id', u'type': u'INTEGER'},
                                         {u'name': u'master_branch', u'type': u'STRING'},
                                         {u'name': u'master', u'type': u'STRING'},
                                         {u'fields': [{u'name': u'id', u'type': u'INTEGER'},
                                                      {u'name': u'gravatar_id', u'type': u'STRING'},
                                                      {u'name': u'avatar_url', u'type': u'STRING'},
                                                      {u'name': u'login', u'type': u'STRING'},
                                                      {u'name': u'url', u'type': u'STRING'}],
                                          u'name': u'member',
                                          u'type': u'RECORD'},
                                         {u'name': u'name', u'type': u'STRING'},
                                         {u'name': u'number', u'type': u'INTEGER'},
                                         {u'fields': [{u'name': u'action', u'type': u'STRING'},
                                                      {u'name': u'html_url', u'type': u'STRING'},
                                                      {u'name': u'page_name', u'type': u'STRING'},
                                                      {u'name': u'sha', u'type': u'STRING'},
                                                      {u'name': u'summary', u'type': u'STRING'},
                                                      {u'name': u'title', u'type': u'STRING'}],
                                          u'mode': u'REPEATED',
                                          u'name': u'pages',
                                          u'type': u'RECORD'},
                                         {u'fields': [{u'name': u'additions', u'type': u'INTEGER'},
                                                      {u'fields': [{u'fields': [{u'name': u'clone_url', u'type': u'STRING'},
                                                                                {u'name': u'created_at', u'type': u'STRING'},
                                                                                {u'name': u'description', u'type': u'STRING'},
                                                                                {u'name': u'fork', u'type': u'BOOLEAN'},
                                                                                {u'name': u'forks', u'type': u'INTEGER'},
                                                                                {u'name': u'git_url', u'type': u'STRING'},
                                                                                {u'name': u'has_downloads', u'type': u'BOOLEAN'},
                                                                                {u'name': u'has_issues', u'type': u'BOOLEAN'},
                                                                                {u'name': u'has_wiki', u'type': u'BOOLEAN'},
                                                                                {u'name': u'homepage', u'type': u'STRING'},
                                                                                {u'name': u'html_url', u'type': u'STRING'},
                                                                                {u'name': u'id', u'type': u'INTEGER'},
                                                                                {u'name': u'language', u'type': u'STRING'},
                                                                                {u'name': u'master_branch', u'type': u'STRING'},
                                                                                {u'name': u'name', u'type': u'STRING'},
                                                                                {u'name': u'open_issues', u'type': u'INTEGER'},
                                                                                {u'fields': [{u'name': u'id', u'type': u'INTEGER'},
                                                                                             {u'name': u'gravatar_id', u'type': u'STRING'},
                                                                                             {u'name': u'avatar_url', u'type': u'STRING'},
                                                                                             {u'name': u'login', u'type': u'STRING'},
                                                                                             {u'name': u'url', u'type': u'STRING'}],
                                                                                 u'name': u'owner',
                                                                                 u'type': u'RECORD'},
                                                                                {u'name': u'private', u'type': u'BOOLEAN'},
                                                                                {u'name': u'pushed_at', u'type': u'STRING'},
                                                                                {u'name': u'size', u'type': u'INTEGER'},
                                                                                {u'name': u'ssh_url', u'type': u'STRING'},
                                                                                {u'name': u'svn_url', u'type': u'STRING'},
                                                                                {u'name': u'updated_at', u'type': u'STRING'},
                                                                                {u'name': u'watchers', u'type': u'INTEGER'},
                                                                                {u'name': u'url', u'type': u'STRING'}],
                                                                    u'name': u'repo',
                                                                    u'type': u'RECORD'},
                                                                   {u'name': u'sha', u'type': u'STRING'},
                                                                   {u'name': u'ref', u'type': u'STRING'},
                                                                   {u'fields': [{u'name': u'id', u'type': u'INTEGER'},
                                                                                {u'name': u'gravatar_id', u'type': u'STRING'},
                                                                                {u'name': u'avatar_url', u'type': u'STRING'},
                                                                                {u'name': u'login', u'type': u'STRING'},
                                                                                {u'name': u'url', u'type': u'STRING'}],
                                                                    u'name': u'user',
                                                                    u'type': u'RECORD'},
                                                                   {u'name': u'label', u'type': u'STRING'}],
                                                       u'name': u'base',
                                                       u'type': u'RECORD'},
                                                      {u'name': u'body', u'type': u'STRING'},
                                                      {u'name': u'changed_files', u'type': u'INTEGER'},
                                                      {u'name': u'closed_at', u'type': u'STRING'},
                                                      {u'name': u'comments', u'type': u'INTEGER'},
                                                      {u'name': u'commits', u'type': u'INTEGER'},
                                                      {u'name': u'created_at', u'type': u'STRING'},
                                                      {u'name': u'deletions', u'type': u'INTEGER'},
                                                      {u'name': u'diff_url', u'type': u'STRING'},
                                                      {u'fields': [{u'fields': [{u'name': u'clone_url', u'type': u'STRING'},
                                                                                {u'name': u'created_at', u'type': u'STRING'},
                                                                                {u'name': u'description', u'type': u'STRING'},
                                                                                {u'name': u'fork', u'type': u'BOOLEAN'},
                                                                                {u'name': u'forks', u'type': u'INTEGER'},
                                                                                {u'name': u'git_url', u'type': u'STRING'},
                                                                                {u'name': u'has_downloads', u'type': u'BOOLEAN'},
                                                                                {u'name': u'has_issues', u'type': u'BOOLEAN'},
                                                                                {u'name': u'has_wiki', u'type': u'BOOLEAN'},
                                                                                {u'name': u'homepage', u'type': u'STRING'},
                                                                                {u'name': u'html_url', u'type': u'STRING'},
                                                                                {u'name': u'id', u'type': u'INTEGER'},
                                                                                {u'name': u'language', u'type': u'STRING'},
                                                                                {u'name': u'master_branch', u'type': u'STRING'},
                                                                                {u'name': u'name', u'type': u'STRING'},
                                                                                {u'name': u'open_issues', u'type': u'INTEGER'},
                                                                                {u'fields': [{u'name': u'id', u'type': u'INTEGER'},
                                                                                             {u'name': u'gravatar_id', u'type': u'STRING'},
                                                                                             {u'name': u'avatar_url', u'type': u'STRING'},
                                                                                             {u'name': u'login', u'type': u'STRING'},
                                                                                             {u'name': u'url', u'type': u'STRING'}],
                                                                                 u'name': u'owner',
                                                                                 u'type': u'RECORD'},
                                                                                {u'name': u'private', u'type': u'BOOLEAN'},
                                                                                {u'name': u'pushed_at', u'type': u'STRING'},
                                                                                {u'name': u'size', u'type': u'INTEGER'},
                                                                                {u'name': u'ssh_url', u'type': u'STRING'},
                                                                                {u'name': u'svn_url', u'type': u'STRING'},
                                                                                {u'name': u'updated_at', u'type': u'STRING'},
                                                                                {u'name': u'watchers', u'type': u'INTEGER'},
                                                                                {u'name': u'url', u'type': u'STRING'}],
                                                                    u'name': u'repo',
                                                                    u'type': u'RECORD'},
                                                                   {u'name': u'sha', u'type': u'STRING'},
                                                                   {u'name': u'ref', u'type': u'STRING'},
                                                                   {u'fields': [{u'name': u'id', u'type': u'INTEGER'},
                                                                                {u'name': u'gravatar_id', u'type': u'STRING'},
                                                                                {u'name': u'avatar_url', u'type': u'STRING'},
                                                                                {u'name': u'login', u'type': u'STRING'},
                                                                                {u'name': u'url', u'type': u'STRING'}],
                                                                    u'name': u'user',
                                                                    u'type': u'RECORD'},
                                                                   {u'name': u'label', u'type': u'STRING'}],
                                                       u'name': u'head',
                                                       u'type': u'RECORD'},
                                                      {u'name': u'html_url', u'type': u'STRING'},
                                                      {u'name': u'issue_url', u'type': u'STRING'},
                                                      {u'name': u'id', u'type': u'INTEGER'},
                                                      {u'fields': [{u'fields': [{u'name': u'href', u'type': u'STRING'}],
                                                                    u'name': u'self',
                                                                    u'type': u'RECORD'},
                                                                   {u'fields': [{u'name': u'href', u'type': u'STRING'}],
                                                                    u'name': u'html',
                                                                    u'type': u'RECORD'},
                                                                   {u'fields': [{u'name': u'href', u'type': u'STRING'}],
                                                                    u'name': u'review_comments',
                                                                    u'type': u'RECORD'},
                                                                   {u'fields': [{u'name': u'href', u'type': u'STRING'}],
                                                                    u'name': u'comments',
                                                                    u'type': u'RECORD'}],
                                                       u'name': u'_links',
                                                       u'type': u'RECORD'},
                                                      {u'name': u'mergeable', u'type': u'BOOLEAN'},
                                                      {u'name': u'merged', u'type': u'BOOLEAN'},
                                                      {u'name': u'merged_at', u'type': u'STRING'},
                                                      {u'fields': [{u'name': u'id', u'type': u'INTEGER'},
                                                                   {u'name': u'gravatar_id', u'type': u'STRING'},
                                                                   {u'name': u'avatar_url', u'type': u'STRING'},
                                                                   {u'name': u'login', u'type': u'STRING'},
                                                                   {u'name': u'url', u'type': u'STRING'}],
                                                       u'name': u'merged_by',
                                                       u'type': u'RECORD'},
                                                      {u'name': u'number', u'type': u'INTEGER'},
                                                      {u'name': u'patch_url', u'type': u'STRING'},
                                                      {u'name': u'review_comments', u'type': u'INTEGER'},
                                                      {u'name': u'state', u'type': u'STRING'},
                                                      {u'name': u'title', u'type': u'STRING'},
                                                      {u'name': u'updated_at', u'type': u'STRING'},
                                                      {u'name': u'url', u'type': u'STRING'},
                                                      {u'fields': [{u'name': u'id', u'type': u'INTEGER'},
                                                                   {u'name': u'gravatar_id', u'type': u'STRING'},
                                                                   {u'name': u'avatar_url', u'type': u'STRING'},
                                                                   {u'name': u'login', u'type': u'STRING'},
                                                                   {u'name': u'url', u'type': u'STRING'}],
                                                       u'name': u'user',
                                                       u'type': u'RECORD'}],
                                          u'name': u'pull_request',
                                          u'type': u'RECORD'},
                                         {u'name': u'ref', u'type': u'STRING'},
                                         {u'name': u'ref_type', u'type': u'STRING'},
                                         {u'name': u'size', u'type': u'INTEGER'},
                                         {u'fields': [{u'name': u'encoded', u'type': u'STRING'},
                                                      {u'name': u'actor_email', u'type': u'STRING'},
                                                      {u'name': u'message', u'type': u'STRING'},
                                                      {u'name': u'actor_login', u'type': u'STRING'}],
                                          u'mode': u'REPEATED',
                                          u'name': u'shas',
                                          u'type': u'RECORD'},
                                         {u'fields': [{u'name': u'login', u'type': u'STRING'},
                                                      {u'name': u'repos', u'type': u'INTEGER'},
                                                      {u'name': u'followers', u'type': u'INTEGER'},
                                                      {u'name': u'id', u'type': u'INTEGER'},
                                                      {u'name': u'gravatar_id', u'type': u'STRING'}],
                                          u'name': u'target',
                                          u'type': u'RECORD'},
                                         {u'name': u'url', u'type': u'STRING'}],
                             u'name': u'payload',
                             u'type': u'RECORD'},
                            {u'name': u'url', u'type': u'STRING'},
                            {u'name': u'type', u'type': u'STRING'}]

    parsed = {u'actor': u'foo',
              u'actor_attributes': {u'blog': u'http://foo.com/',
                                    u'company': u'Flickr',
                                    u'email': u'd+github@foo.com',
                                    u'gravatar_id': u'94c21234567890abcdef25e704b88407',
                                    u'location': u'San Francisco, California',
                                    u'login': u'foo',
                                    u'name': u'Foo Bar',
                                    u'type': u'User'},
              u'created_at': u'2012/03/15 00:00:01 -0700',
              u'payload': {u'action': None,
                           u'after': None,
                           u'before': None,
                           u'comment': {},
                           u'comment_id': None,
                           u'commit': None,
                           u'desc': None,
                           u'description': None,
                           u'head': u'2de950123456789abcdef01234451feaf8ce6ae',
                           u'id': None,
                           u'issue': None,
                           u'issue_id': None,
                           u'master': None,
                           u'master_branch': None,
                           u'member': {},
                           u'name': None,
                           u'number': None,
                           u'pages': [],
                           u'pull_request': {},
                           u'ref': u'refs/heads/master',
                           u'ref_type': None,
                           u'shas': [{u'actor_email': u'd+github@foo.com',
                                      u'actor_login': u'Foo Bar',
                                      u'encoded': u'2de958ab480eabe2501b343425b451feaf8ce6ae',
                                      u'message': u'Foo tastes good.'}],
                           u'size': 1,
                           u'target': {},
                           u'url': None},
              u'public': True,
              u'repository': {u'created_at': u'2011/04/12 20:04:19 -0700',
                              u'description': u'A website.',
                              u'fork': False,
                              u'forks': 17,
                              u'has_downloads': True,
                              u'has_issues': True,
                              u'has_wiki': True,
                              u'homepage': u'http://foo.com/',
                              u'integrate_branch': None,
                              u'language': u'Ruby',
                              u'master_branch': None,
                              u'name': u'foo',
                              u'open_issues': 0,
                              u'organization': None,
                              u'owner': u'foo',
                              u'private': False,
                              u'pushed_at': u'2012/03/15 00:00:00 -0700',
                              u'size': 424,
                              u'url': u'https://github.com/foo',
                              u'watchers': 95},
              u'type': u'PushEvent',
              u'url': u'https://github.com/compare/d3e91cb736...2de958ab48'}

    self.assertEqual(parsed, bq._parser.Parser.parse_row(github_nested_schema, data))
