# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM debian:jessie

# Setup base packages
RUN echo "deb-src http://ftp.us.debian.org/debian testing main" >> /etc/apt/sources.list && \
    apt-get update -y && \
    apt-get install --no-install-recommends -y -q \
        curl git wget unzip vim pandoc ca-certificates build-essential \
        libpng-dev libfreetype6-dev && \
    mkdir -p /packages && \
    mkdir -p /tools && \
    mkdir -p /env/python && \
    mkdir -p /env/static && \
    cd /packages && apt-get source -d python-zmq && cd /


# Setup Nodejs
RUN mkdir /node && curl http://nodejs.org/dist/v0.10.32/node-v0.10.32-linux-x64.tar.gz | \
    tar xvzf - -C /node --strip-components=1


# Setup Python and Python Libraries
RUN apt-get install --no-install-recommends -y -q \
    python2.7 python-pip python-dev libatlas-base-dev gfortran
RUN pip install -U tornado==4.0.2 pyzmq==14.3.1 jinja2==2.7.3 && \
    pip install -U pandocfilters==1.2.2 pandas==0.14.1 && \
    pip install -U numpy==1.9.0 && \
    pip install -U patsy==0.3.0 scikit-learn==0.15.2 scipy==0.14.0 && \
    pip install -U sympy==0.7.5 matplotlib==1.4.0 ggplot==0.6.5 && \
    pip install -U statsmodels==0.5.0 && \
    pip install -U oauth2client==1.3 httplib2==0.9 && \
    pip install -U ipython==2.4.1


# Setup Google Cloud SDK
RUN wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip && \
    unzip google-cloud-sdk.zip -d tools && \
    rm google-cloud-sdk.zip
RUN /tools/google-cloud-sdk/install.sh --usage-reporting=false --path-update=true \
        --bash-completion=true --rc-path=/.bashrc --disable-installation-options && \
    /tools/google-cloud-sdk/bin/gcloud -q components update


# Add License file
ADD License.txt /License.txt


# Setup Environment
ENV PATH $PATH:/node/bin:/tools:/tools/google-cloud-sdk/bin
ENV IPYTHON_VERSION _version_
ENV IPYTHON_ENV cloud
ENV DATALAB_ENV docker
ENV PYTHONPATH /env/python


# Add SDK Libraries
ADD build/python/PyGCP-0.1.0.tar.gz /sdk/
ADD build/python/IPythonGCP-0.1.0.tar.gz /sdk/

RUN cd /sdk/PyGCP-0.1.0 && python setup.py install && \
    cd /sdk/IPythonGCP-0.1.0 && python setup.py install


# Setup IPython Profile and Proxy Server
ADD build/ipython.tar.gz /
RUN cd /ipython/proxy && npm install && cd /


# Startup
EXPOSE 8080
VOLUME [ "/var/log/ipython" ]
ENTRYPOINT [ "node", "/ipython/proxy/app.js" ]
