# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM datalab-base
MAINTAINER Google Cloud DataLab

# Add build artifacts
ADD build/web/nb /datalab/web
ADD content/ /datalab

# Install the build artifacts
RUN ln -s /datalab/web/static/datalab.css /datalab/nbconvert/datalab.css && \
    cd /datalab/web && /tools/node/bin/npm install && \
    cd / && \

# Install the support for connecting to a kernel gateway
    wget https://github.com/jupyter/kernel_gateway_demos/archive/e653b2bd3ca91ef1af2a13c397766484dcb7b76d.zip && \
    unzip -qq e653b2bd3ca91ef1af2a13c397766484dcb7b76d.zip -d kernel_gateway_demos && \
    rm e653b2bd3ca91ef1af2a13c397766484dcb7b76d.zip && \
    cd ./kernel_gateway_demos/kernel_gateway_demos-e653b2bd3ca91ef1af2a13c397766484dcb7b76d && \
    pip install ./nb2kg/

ENV EXPERIMENTAL_KERNEL_GATEWAY_URL=""

# Startup
ENV DATALAB_VERSION _version_
ENV DATALAB_COMMIT _commit_
ENV DEPLOY_VM "false"
ENV ENABLE_USAGE_REPORTING true
ENV CLI_LOGIN false

# Startup
ENTRYPOINT [ "/datalab/run.sh" ]
